name: Security CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write
  security-events: write
  pull-requests: write

jobs:
  sast:
    name: SAST - Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config p/ci --sarif --output semgrep-results.sarif

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: semgrep-results.sarif

  sca:
    name: SCA - Dependency Check
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Security-CI"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: reports

  dast:
    name: DAST - OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: sca
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start application (staging)
        run: |
          docker compose up -d
          sleep 10

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://localhost:8080"
          cmd_options: "-a -r zap_report.html"

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: zap_report.html
