name: Security CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  semgrep:
    name: SAST - semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install semgrep
        run: python -m pip install semgrep
      - name: Run semgrep (SAST)
        run: semgrep --config=.semgrep.yml --json > semgrep-report.json || true
      - name: Upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

  zap:
    name: DAST - OWASP ZAP baseline
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Start ZAP baseline scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'http://example-app:8080' # update to your staging URL
          format: 'json'
          output: 'zap-report.json'
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.json

  sca:
    name: SCA - Dependency scanning (OWASP Dependency-Check)
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Install dependency-check
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.2/dependency-check-8.3.2-release.zip
          unzip dependency-check.zip
      - name: Run dependency-check
        run: ./dependency-check/bin/dependency-check.sh --project "project" --scan . --format JSON --out dependency-check-report.json || true
      - name: Upload dependency-check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.json
